source "https://rubygems.org"

gem "jekyll", "~> 4.3"
gem "jekyll-paginate"
gem "jekyll-seo-tag"
gem "jekyll-sitemap"
gem "jekyll-youtube"
gem "jekyll-github-metadata"
gem "jekyll-gist"
gem "jekyll-relative-links"
gem "webrick", "~> 1.8"